package constants

const (
	WINDOW_WIDTH  = 1024
	WINDOW_HEIGHT = 768
	SPRITE_WIDTH  = 32
	SPRITE_HEIGHT = 32
	WORLD_WIDTH   = WINDOW_WIDTH / SPRITE_WIDTH
	WORLD_HEIGHT  = WINDOW_HEIGHT / SPRITE_HEIGHT
)
